# Generated by Django 4.0.5 on 2022-07-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancecheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
